app:
  generation:
    amount: 100

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:${MONGO_PASSWORD}@cluster0.orp32.mongodb.net/college?retryWrites=true&w=majority
#      uri: mongodb://localhost:27017/college

logging:
  level:
    telran: info

server:
  port: 8080

java:
  runtime:
    version: 17
